export default {
  AUTH_USER: 'AUTH_USER',
  ROLE_STUDENT: 'ROLE_AOAdmin',
  PROFILE_URL: 'https://s3.amazonaws.com/',
  PROFILE: 'PROFILE',
  REMEMBER_ME: 'REMEMBER_ME',
  CURRENT_ASSIGNMENTS: 'Current Assignment',
  VIEW_ALL: 'VIEW ALL',
  DASHBOARD: 'DASHBOARD',
  LEARNING: 'Learning',
  INSIGHTS: 'Insights',
  Manage: 'Manage',
  Explore: 'Explore',
  Take: 'Take',
  EDIT_ASSIGNMENT: 'EDIT ASSIGNMENT',
  VIEW_ASSIGNMENT: 'VIEW ASSIGNMENT',
  READ_MORE: 'READ MORE',
  Something_went_wrong: 'Something went wrong',
  Wrong_Credentails: 'Wrong Credentails',
  Token_expired: 'Token expired',
  profile_image: 'gtgusermedia/45770/Thanks Givingjpeg',
  HTTP_ERROR_CODE: 'HTTP_ERROR',
  SERVER_NOT_FOUND: 'SERVER_NOT_FOUND',
  UNAUTHORIZED_ACCESS_CODE: 'UNAUTHORIZED_ACCESS',
  paragraph: 'There are no new insights at this time.',
  paragraph_check: ' Check back later for more updates!',
};
